services:
  shortcuter:
    build: .
    container_name: shortcuter
    ports:
      - "8000:8000"
    volumes:
      - ./shortcuts.yaml:/shortcuts.yaml:ro
      - icon-cache:/app/api/icon-cache
    restart: unless-stopped

volumes:
  icon-cache:
